module.exports =	{ OnOff				: "openHab_op_OnOff"
					, IncreaseDecrease	: "openHab_op_IncreaseDecrease"
					, Percent			: "openHab_op_Percent"
					, OpenClosed		: "openHab_op_OpenClosed"
					, Decimal			: "openHab_op_Decimal"
					, UpDown			: "openHab_op_UpDown"
					, StopMove			: "openHab_op_StopMove"
					, String			: "openHab_op_String"
					, HSB				: "openHab_op_HSB"
					};